version: '3'
volumes:
  postgres:
services:
  db:
    image: postgres:13-alpine
    ports:
      - 45432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
